name: Deploy QuestionsApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Publish
        run: dotnet publish Questions.csproj -c Release

      - name: Replace public with published files
        run: |
          rm -rf public/*
          cp -r bin/Release/net10.0/publish/wwwroot/. public/

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel deploy public --prod --token="${{ secrets.VERCEL_TOKEN }}" --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
